### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by 10016411**

### CODE REVIEW

**Comment by beak2825** [comment]
Email me perosonsybs@gmail.com for a totally offline game website that does include getaway shootout. 
image

**Comment by PunchmadeDav** [comment]
took a look at your account. Your getaway shootout that is found in OPENME.zip is not offline. you are using github to host files to bypass CORS. My getaway shootout is completely offline WITHOUT using 3rd party services. It is achieved using base64 encoding. If you would like to prove me wrong i have gmailed you, just send the zip and ill see whether or not its true.

**Comment by beak2825** [comment]
Hey, thanks for emailing me. by the way that repo was just a proof of
concept, and not the final version of my games.
Here is the FULLY offline version of games.
By the way do you mind sending me the python scripts you used (if any) for
dividing the base64 files or anything else like that? Mine are included in
the files.
https://drive.google.com/file/d/1w9Y8guZE4kFYFfCpOSNUoAa2m2UWVnJx/view?usp=sharing

**Comment by PunchmadeDav** [comment]
i didnt use any python scripts, just base64encode.org, Are some of your games taken from repos similar to this or all self made btw? This repo was made just for a pull request on Mountain's Offline Games repo, my gamesite is still a wip, it will have games like buckshot roulette, The actual geometry dash games, and multiple minecraft (eaglercraft) versions, aswell as a slimerancher port to browser. 
Capture
These are the finished games as of now

**Comment by PunchmadeDav** [comment]
I also have FNAF 1-4, World, UCN, and PS

**Comment by PunchmadeDav** [comment]
shouldve mentioned that 10016411 and this acc are the same, 10016411 is just under my other gmail

**Comment by beak2825** [comment]
All of the games on there I had not taken from any repo except learntofly1
2 and 3, bloonstd1 2 and 5, burrito bison and drivemad were taken from the
gams-offline repo, everything else was manually set for offline use by me

**Comment by beak2825** [comment]
Also it's possible to use python scripts for a lot of things, including
adding a line for everypage.js or some github apps could do the trick

It also would be interesting if we could help eachother out on certain games, some games I cannot figure out because the fetch script is fetching multiple resources at once.

**Comment by PunchmadeDav** [comment]
id be open to helping eachother with games. do you have a discord? my discord is DavDaGeneral

**Comment by PunchmadeDav** [comment]
Hey its been a bit, im still open to working on games together. Also if youd like we can trade games for our gamesites.

**Comment by beak2825** [comment]
Added you on discord. Its vivi

**Pull request merged**
